# Generated by Django 6.0.5 on 2026-05-20 11:47

import account.util
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.user')),
            ],
            options={
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('100', 'Level100'), ('200', 'Level200'), ('300', 'Level300'), ('400', 'Level400'), ('500', 'Level500'), ('600', 'Level600')], default='100', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Withdrawn', 'Withdrawn')], default='Active', max_length=20)),
                ('matric_number', models.CharField(default=account.util.generate_matric_number, max_length=20, unique=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.user')),
            ],
        ),
    ]
