# Generated by Django 6.0.5 on 2026-06-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='entry_year',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
