# Generated by Django 6.0.5 on 2026-06-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='department',
            table='core_department',
        ),
    ]
